### ISSUE TITLE
da, leaves space for first parameter

### ISSUE THREAD

**Issue by mortenbh** [sgur/vim-textobj-parameter#1]
Placing the cursor on the first argument in `foo(aa, bb)` and pressing `da,` produces `foo( bb)`. Ideally, it would produce foo(bb).

Perhaps related, placing the cursor over the second argument in `foo(aa , bb)` and pressing `da,` produces `foo(aa )`. Again, it would be great if the extra space was removed.

Note, in both cases more than one space can be present, and I think it would be natural if all such spaces were removed.

**Comment by sgur** [comment]
Verified.
I'll fix it.

**Comment by sgur** [comment]
> Perhaps related, placing the cursor over the second argument in foo(aa , bb) and pressing da, produces foo(aa ). Again, it would be great if the extra space was removed.

Oops, I've forgotten the case.
